"""
Django settings for newsproject project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

import os

# import environ

# # Initialize environ
# env = environ.Env(
#     # set casting, default value
#     ALLOWED_HOSTS=(list, ['localhost', '127.0.0.1']),
# )

# # Reading .env file
# environ.Env.read_env()

# ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=['localhost', '127.0.0.1'])



# # Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent




# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-a9-5fu#511#@la^zl76ivr1)h+51c*_&9=g_wzxwneswjoijd-"
# SECRET_KEY = env('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# ALLOWED_HOSTS = []
ALLOWED_HOSTS = ['192.168.1.22', '127.0.0.1', 'localhost','0.0.0.0','192.168.1.5']
CORS_ALLOW_ALL_ORIGINS = True

# DEBUG = env.bool("DEBUG", default=False)



# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'corsheaders',
    'rest_framework',

    "newsapp",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    'corsheaders.middleware.CorsMiddleware',

    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',

]
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
STATIC_ROOT = BASE_DIR / "staticfiles"


ROOT_URLCONF = "newsproject.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR/"template"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "newsproject.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"


DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"





# settings.py

# URLs for news sources
COLLEGE_NEWS_SOURCE_URLS = {
    "JNTUH": 'https://jntuh.ac.in/notifications',
    "JNTUK": 'https://www.jntuk.edu.in/category/notifications/',
    # Add more sources as needed
}

# RSS feed URLs
EDUCATION_RSS_FEED_URLS = {
    "Times of India": "https://timesofindia.indiatimes.com/rssfeeds/913168846.cms",
    "OneIndia": "https://www.oneindia.com/rss/feeds/oneindia-fb.xml",
    
    "theweek":"https://www.theweek.in/education/exams.rss.html",
    "andhrajyothy":"https://www.andhrajyothy.com/rss/gn/education/feed.xml",
    "news18": "https://www.thehindu.com/sci-tech/science/?service=rss",
    # Add more feeds as needed
}

# TSPSC notifications URL
TSPSC_NOTIFICATIONS_URL = 'https://websitenew.tspsc.gov.in/notifications'
